// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6vubecuUUJDuWdza-WyjIjPnhCuuKdxI',
    appId: '1:913264173180:web:da3bd68a6651572de169f9',
    messagingSenderId: '913264173180',
    projectId: 'flutter-notification-6a9d2',
    authDomain: 'flutter-notification-6a9d2.firebaseapp.com',
    storageBucket: 'flutter-notification-6a9d2.firebasestorage.app',
    measurementId: 'G-VZJ63TB4C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVL56aMyAJiU7U55BKhyuDCDCKwgIFTIU',
    appId: '1:913264173180:android:8a4c3c1887aa4d2de169f9',
    messagingSenderId: '913264173180',
    projectId: 'flutter-notification-6a9d2',
    storageBucket: 'flutter-notification-6a9d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTFxq-YZQgr2nHgpGMuLBvNx1uOBx8kf0',
    appId: '1:913264173180:ios:ea6a02fb380bd376e169f9',
    messagingSenderId: '913264173180',
    projectId: 'flutter-notification-6a9d2',
    storageBucket: 'flutter-notification-6a9d2.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTFxq-YZQgr2nHgpGMuLBvNx1uOBx8kf0',
    appId: '1:913264173180:ios:ea6a02fb380bd376e169f9',
    messagingSenderId: '913264173180',
    projectId: 'flutter-notification-6a9d2',
    storageBucket: 'flutter-notification-6a9d2.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6vubecuUUJDuWdza-WyjIjPnhCuuKdxI',
    appId: '1:913264173180:web:3c531d6a513f9c95e169f9',
    messagingSenderId: '913264173180',
    projectId: 'flutter-notification-6a9d2',
    authDomain: 'flutter-notification-6a9d2.firebaseapp.com',
    storageBucket: 'flutter-notification-6a9d2.firebasestorage.app',
    measurementId: 'G-SF8TV8C30M',
  );
}
